name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.2
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Zig Testing
        run: zig build unit_test
      - name: Build zig library
        run: zig build wasm
      - name: Install Dependices
        run: zig build install_npm_deps

      - name: Build Library
        run: zig build build_all
      - name: Run Test
        run: zig build test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
